// playground/react-app/src/Button.js
import React, { useState, useCallback, useRef, useEffect } from 'react';
import ButtonNative from '../../../bundles/react/button-native';
import ButtonWrapper from '../../../bundles/react/button-wrapper';
import ButtonRenovatedWrapper from '../../../bundles/react/button-renovated-wrapper';

const RUN_COUNT = 200;

const buttons = [];

const addPerformanceTest = (name, params) => {
  buttons.push({ name, ...params });
}

addPerformanceTest('clear', {
  initialOptions: null
});

addPerformanceTest('create', {
  initialOptions: { text: 'button' }
});

addPerformanceTest('Minimum options', {
  initialOptions: { text: 'button' }
});

addPerformanceTest('Maximum options', {
  initialOptions: {
      text: 'button',
      icon: 'download',
      accessKey: 'c',
      activeStateEnabled: true,
      disabled: false,
      elementAttr: { 'data-fake': 123 },
      hint: 'text hint',
      onClick: () => undefined,
      rtlEnabled: true,
      tabIndex: 1,
      width: 100,
      height: '40'
  }
});

const ButtonTemplate = () => <div>Button Template</div>

addPerformanceTest('With template', {
  initialOptions: {
      text: 'button',
      component: ButtonTemplate
  }
});

addPerformanceTest('Option icon change', {
  updateOptions: { icon: 'download' }
});

addPerformanceTest('Option text change', {
  updateOptions: { text: 'New Button Text' }
});

addPerformanceTest('Option useInkRipple change', {
  updateOptions: { useInkRipple: true }
});

addPerformanceTest('Method onFocus', {
  methodName: 'focus'
});

addPerformanceTest('Options full set change', {
  updateOptions: {
      text: 'button2',
      icon: 'download',
      accessKey: 'c',
      activeStateEnabled: true,
      disabled: false,
      elementAttr: { 'data-fake': 123 },
      hint: 'text hint',
      onClick: () => undefined,
      rtlEnabled: true,
      tabIndex: 1,
      width: 100,
      height: '40px'
  }
});

const TestButtons = (props) => {
  return <div id="test-buttons">
    {buttons.map((params, index) => 
      <input key={index} type='button' value={params.name} onClick={() => props.onClick(params) } />
    )}
  </div>;
}

const getWidget = (type) => {
  console.log(type);
  if(type === 'renovated') {
    return ButtonNative;
  } else if(type === 'renovatedwrapper') {
    return ButtonRenovatedWrapper;
  } else {
    return ButtonWrapper;
  }
}

function ButtonPage(props) {
  const type = props.match.params.type;
  const Widget = getWidget(type);
  const [options, setOptions] = useState(null);
  const widgetsRef = useRef([]);

  useEffect(() => {
    if(!options) {
      widgetsRef.current = [];
    }
  }, [!options]);

  const onClick = useCallback(({ name, initialOptions, updateOptions, methodName }) => {
    performance.mark("start");
    console.time(name);
    if(initialOptions !== undefined) {
      setOptions(initialOptions);
    }
    if(updateOptions !== undefined) {
      setOptions({...options, ...updateOptions});
    }
    if(methodName) {
      widgetsRef.current.forEach((widget) => {
        const instance = widget.instance || widget;
        instance[methodName]();
      });
    }
    requestAnimationFrame(() => {
      console.timeEnd(name);
      performance.mark("end")
      performance.measure(name, 'start', 'end');
    })
  }, [options]);

  return (
    <>
      <h2>button {type}</h2>
      <TestButtons onClick={onClick} />
      <div id="workspace">
        {options && Array.from({ length: RUN_COUNT }).map((_, index) => 
          <Widget 
            key={index} 
            ref={el => widgetsRef.current[index] = el} 
            {...options}
          />
        )}
      </div>
    </>
  );
};

export default ButtonPage;

// playground/vue-app/src/components/Button.vue
<template>
  <div>
    <h1>button {{type}}</h1>
    <div class="test-buttons">
      <input
        v-for="test in testButtons"
        :key="test.name"
        type="button"
        :value="test.name"
        v-on:click="test.func()"
      />
    </div>
    <div class="workspace">
      <template v-if="type == 'basic' && options">
        <dx-button-basic
          v-for="key in keys"
          :key="key"
          ref="button"
          v-bind="options"
        >
          <template v-if="template">
            <div>Button Template</div>
          </template>
        </dx-button-basic>
      </template>
      <template v-if="type == 'renovated' && options">
        <dx-button-renovated
          v-for="key in keys"
          :key="key"
          ref="button"
          v-bind="options"
        >
          <template v-if="template">
            <div>Button Template</div>
          </template>
        </dx-button-renovated>
      </template>
      <template v-if="type == 'renovatedwrapper' && options">
        <dx-button-renovated-wrapper
          v-for="key in keys"
          :key="key"
          ref="button"
          v-bind="options"
        >
          <template v-if="template">
            <div>Button Template</div>
          </template>
        </dx-button-renovated-wrapper>
      </template>
    </div>
  </div>
</template>

<script>
import DxButtonBasic from './button-wrapper';
import DxButtonRenovated from './button-native';
import DxButtonRenovatedWrapper from './button-renovated-wrapper';

export default {
  name: 'Button',
  props: ['type'],
  components: {
    DxButtonBasic,
    DxButtonRenovated,
    DxButtonRenovatedWrapper
  },
  data() {
    const testButtons = [];

    function addPerformanceTest(name, func) {
      testButtons.push({ name, func: () => {
        performance.mark("start");
        console.time(name);
        func();
        requestAnimationFrame(() => {
          console.timeEnd(name);
          performance.mark("end")
          performance.measure(name, 'start', 'end');
        });
      } });
    }

    addPerformanceTest('clear', () => {
      this.options = null;
      this.template = false;
    });
    addPerformanceTest('create', () => {
      this.options = { text: 'button' };
      this.template = false;
    });
    addPerformanceTest('Minimum options', () => {
      this.options = { text: 'button' };
      this.template = false;
    });
    addPerformanceTest('Maximum options', () => {
      this.options = {
        text: 'button',
        icon: 'download',
        accessKey: 'c',
        activeStateEnabled: true,
        disabled: false,
        elementAttr: { 'data-fake': 123 },
        hint: 'text hint',
        onClick: () => undefined,
        rtlEnabled: true,
        tabIndex: 1,
        width: 100,
        height: '40'
      };
    });
    addPerformanceTest('With template', () => {
      this.template = true;
      this.options = { text: 'button' };
    });
    addPerformanceTest('Option icon change', () => {
      this.options.icon = 'download';
    });
    addPerformanceTest('Option text change', () => {
      this.options.text = 'New Button Text';
    });
    addPerformanceTest('Option useInkRipple change', () => {
      this.options.useInkRipple = true;
    });
    addPerformanceTest('Options full set change', () => {
      this.options = {
        text: 'button2',
        icon: 'download',
        accessKey: 'c',
        activeStateEnabled: true,
        disabled: false,
        elementAttr: { 'data-fake': 123 },
        hint: 'text hint',
        onClick: () => undefined,
        rtlEnabled: true,
        tabIndex: 1,
        width: 100,
        height: '40'
      };
    });
    addPerformanceTest('Method onFocus', () => {
      this.$refs.button.forEach((widget) => {
        const instance = widget.instance || widget;
        instance.focus();
      });
    });

    const keys = [];

    for(let i = 0; i < 200; i++) {
      keys.push(i);
    }

    return {
      testButtons,
      keys,
      template: false,
      options: null,
    };
  },
}
</script>
