// playground/react-app/src/CheckBox.js
import React, { useState, useCallback, useRef, useEffect } from 'react';

import CheckBoxNative from '../../../bundles/react/check_box-native';
import CheckBoxWrapper from '../../../bundles/react/check_box-wrapper';
import CheckBoxRenovatedWrapper from '../../../bundles/react/check_box-renovated-wrapper';
// import CheckBoxPrev from 'devextreme-react/check_box';

const RUN_COUNT = 200;

const check_boxs = [];

const addPerformanceTest = (name, params) => {
  check_boxs.push({ name, ...params });
}

addPerformanceTest('clear', {
  initialOptions: null
});

addPerformanceTest('create', {
  initialOptions: { value: true }
});

addPerformanceTest('Minimum options', {
  initialOptions: { value: true }
});

addPerformanceTest('Option value change', {
  updateOptions: { value: false }
});

addPerformanceTest('Method onFocus', {
  methodName: 'focus'
});

const TestButtons = (props) => {
  return <div id="test-buttons">
    {check_boxs.map((params, index) => 
      <input key={index} type='button' value={params.name} onClick={() => props.onClick(params) } />
    )}
  </div>;
}

const getWidget = (type) => {
  console.log(type);
  if(type === 'renovated') {
    return CheckBoxNative;
  } else if(type === 'renovatedwrapper') {
    return CheckBoxRenovatedWrapper;
  } else {
    return CheckBoxWrapper;
  }
}

function CheckBoxPage(props) {
  const type = props.match.params.type;
  const Widget = getWidget(type);
  const [options, setOptions] = useState(null);
  const widgetsRef = useRef([]);

  useEffect(() => {
    if(!options) {
      widgetsRef.current = [];
    }
  }, [!options]);

  const onClick = useCallback(({ name, initialOptions, updateOptions, methodName }) => {
    performance.mark("start");
    console.time(name);
    if(initialOptions !== undefined) {
      setOptions(initialOptions);
    }
    if(updateOptions !== undefined) {
      setOptions({...options, ...updateOptions});
    }
    if(methodName) {
      widgetsRef.current.forEach((widget) => {
        const instance = widget.instance || widget;
        instance[methodName]();
      });
    }
    window['requestIdleCallback'](() => {
      console.timeEnd(name);
      performance.mark("end")
      performance.measure(name, 'start', 'end');
    });
  }, [options]);

  return (
    <>
      <h2>check_box {type}</h2>
      <TestButtons onClick={onClick} />
      <div id="workspace">
        {options && Array.from({ length: RUN_COUNT }).map((_, index) => 
          <Widget 
            key={index} 
            ref={el => widgetsRef.current[index] = el} 
            {...options}
          />
        )}
      </div>
    </>
  );
};

export default CheckBoxPage;

// playground/vue-app/src/components/CheckBox.vue
<template>
  <div>
    <h1>checkbox {{type}}</h1>
    <div class="test-buttons">
      <input
        v-for="test in testButtons"
        :key="test.name"
        type="button"
        :value="test.name"
        v-on:click="test.func()"
      />
    </div>
    <div class="workspace">
      <template v-if="type == 'basic' && options">
        <dx-check-box-basic
          v-for="key in keys"
          :key="key"
          ref="check_box"
          v-bind="options"
        >
        </dx-check-box-basic>
      </template>
      <template v-if="type == 'renovated' && options">
        <dx-check-box-renovated
          v-for="key in keys"
          :key="key"
          ref="check_box"
          v-bind="options"
        >
        </dx-check-box-renovated>
      </template>
      <template v-if="type == 'renovatedwrapper' && options">
        <dx-check-box-renovated-wrapper
          v-for="key in keys"
          :key="key"
          ref="button"
          v-bind="options"
        >
        </dx-check-box-renovated-wrapper>
      </template>
    </div>
  </div>
</template>

<script>
import DxCheckBoxBasic from './check_box-wrapper';
import DxCheckBoxRenovated from './check_box-native';
import DxCheckBoxRenovatedWrapper from './check_box-renovated-wrapper';

export default {
  name: 'CheckBox',
  props: ['type'],
  components: {
    DxCheckBoxBasic,
    DxCheckBoxRenovated,
    DxCheckBoxRenovatedWrapper
  },
  data() {
    const testButtons = [];

    function addPerformanceTest(name, func) {
      testButtons.push({ name, func: () => {
        performance.mark("start");
        console.time(name);
        func();
        window['requestIdleCallback'](() => {
          console.timeEnd(name);
          performance.mark("end")
          performance.measure(name, 'start', 'end');
        });
      } });
    }

    addPerformanceTest('clear', () => {
      this.options = null;
      this.template = false;
    });
    addPerformanceTest('create', () => {
      this.options = { value: true };
      this.template = false;
    });
    addPerformanceTest('Minimum options', () => {
      this.options = { value: true };
      this.template = false;
    });
    addPerformanceTest('Option value change', () => {
      this.options.value = false;
    });
    addPerformanceTest('Method onFocus', () => {
      this.$refs.button.forEach((widget) => {
        const instance = widget.instance || widget;
        instance.focus();
      });
    });

    const keys = [];

    for(let i = 0; i < 200; i++) {
      keys.push(i);
    }

    return {
      testButtons,
      keys,
      template: false,
      options: null,
    };
  },
}
</script>
