// playground/react-app/src/App.js
import React, { useEffect, useState, useCallback } from 'react';
import ButtonNative from '../../../bundles/react/button-native';
import ButtonWrapper from '../../../bundles/react/button-wrapper';
import ButtonRenovatedWrapper from '../../../bundles/react/button-renovated-wrapper';

const Widget = ButtonRenovatedWrapper;
const RUN_COUNT = 5000;

const ARRAY = new Array();
let observer = new MutationObserver(mutationRecords => {
  console.log(mutationRecords);
  console.timeLog('Time');
});

const startTime = () => {
  console.clear();
  observer.observe(document.getElementById('root'), {
    childList: true,
    subtree: true,
    characterDataOldValue: true,
    attributes: true,
  });
  console.time('Time');
};

const FirstRenderMin = () => {
  startTime();
  return ARRAY.map((index) => (
    <Widget
      key={index}
      text="button text"
    />
  ));
}
const FirstRenderMax = () => {
  startTime();
  return ARRAY.map((index) => (
    <Widget
      key={index}
      text="button text"
      icon="download"
      accessKey="c"
      activeStateEnabled={true}
      disabled={false}
      elementAttr={{ 'data-fake': 123 }}
      hint="text hint"
      onClick={() => undefined}
      rtlEnabled={true}
      tabIndex={1}
      width={100}
      height="40"
    />
  ));
};
const FirstRenderTemplate = () => {
  startTime();
  return ARRAY.map((index) => (
    <Widget
      key={index}
      template={() => <div>button</div>}
      component={() => <div>button</div>}
    />
  ));
}
const OptionChangeIcon = () => {
  const [icon, setIcon] = useState();
  useEffect(() => {
    setTimeout(() => {

      startTime();
      setIcon('download');
    }, 300);
  }, []);

  return ARRAY.map((index) => <Widget icon={icon} key={index} />);
};
const OptionChangeText = () => {
  const [text, setText] = useState('button');
  useEffect(() => {
    setTimeout(() => {

      startTime();
      setText('new button text');
    }, 300);
  }, []);

  return ARRAY.map((index) => <Widget text={text} key={index} />);
};
const OptionChangeMax = () => {
  const [options, setOptions] = useState({ text: 'button' });
  useEffect(() => {
    setTimeout(() => {

      startTime();
      setOptions({
        text: 'button 123321',
        icon: 'download',
        accessKey: 'c',
        activeStateEnabled: true,
        disabled: false,
        elementAttr: { 'data-fake': 123 },
        hint: 'text hint',
        onClick: () => undefined,
        rtlEnabled: true,
        tabIndex: 1,
        width: 100,
        height: '40',
      });
    }, 300);
  }, []);

  return ARRAY.map((index) => <Widget key={index} {...options} />);
};

const MethodFocus = () => {
  const widgets = [];
  const saveRefs = useCallback((component) => {
    widgets.push(component);
  }, []);
  useEffect(() => {
    startTime();
    widgets.forEach(widget => {
      if (widget.instance !== undefined) {
        widget.instance.focus();
      } else {
        widget.focus();
      }
    });
  }, []);

  return ARRAY.map((index) => <Widget text="button text" key={index} ref={saveRefs} />);
};

const MemoryHeap = () => {
  return ARRAY.map((index) => (
    <Widget
      key={index}
      text="button text"
    />
  ));
}

const MemoryLeaks = () => {
  const [widgets, setWidgets] = useState(ARRAY.slice());
  const create = useCallback(() => {
    setWidgets(ARRAY.slice());
  }, []);
  const remove = useCallback(() => {
    setWidgets([]);
  }, []);

  return(
    <>
      <button onClick={create} />
      <button onClick={remove} />
      {widgets.map((index) => (
        <Widget
          key={index}
          text="button text"
        />
      ))}
  </>
  );
}

function App() {
  for (let i = 0; i < RUN_COUNT; i++) {
    ARRAY.push(i.toString());
  }

  return (
    <>
      {/* <FirstRenderMin /> */}
      {/* <FirstRenderMax /> */}
      {/* <FirstRenderTemplate /> */}
      {/* <OptionChangeIcon /> */}
      {/* <OptionChangeText /> */}
      {/* <OptionChangeMax /> */}
      {/* <MethodFocus /> */}
      {/* <MemoryHeap /> */}
      <MemoryLeaks />
    </>
  );
};

export default App;

// playground/angular-app/src/app/app.component.ts
import { Component, ViewChildren } from '@angular/core';
import { DxButtonComponent } from './button-native';
// import { DxButtonComponent } from './button-wrapper';
// import { DxButtonComponent } from './button-renovated-wrapper';

let observer = new MutationObserver(mutationRecords => {
  console.log(mutationRecords);
  (console as any).timeLog('Time');
});

const startTime = () => {
  console.clear();
  observer.observe(document.getElementById('root'), {
    childList: true,
    subtree: true,
    characterDataOldValue: true,
    attributes: true,
  });
  console.time('Time');
};

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  // @ViewChildren(DxButtonComponent) widgets;

  title = 'custombundleangular8';
  items = Array(500);
  icon = undefined;
  text = 'button text';
  accessKey = "a";
  disabled = false;
  hint = 'hint';
  rtlEnabled = false;
  tabIndex = 0;
  width = 100;
  height = '40';

  constructor() {
    startTime();
    console.time('First render');
  }

  ngAfterViewInit() {
    console.timeEnd('First render');
  }

  clickHandler() {
    return undefined;
  }

  changeIcon() {
    startTime();
    this.icon = 'download';
  }

  changeText() {
    startTime();
    this.text = 'new button text';
  }

  changeOptions() {
    startTime();
    this.icon = 'download';
    this.text = 'new button text';
    this.accessKey = "c";
    this.disabled = false;
    this.hint = 'new hint';
    this.rtlEnabled = true;
    this.tabIndex = 10;
    this.width = 110;
    this.height = '30';
  }

  // focus() {
  //   startTime();
  //   debugger
  //   this.widgets.forEach(widget => {
  //     if (widget.instance !== undefined) {
  //       widget.instance.focus();
  //     } else {
  //       widget.focus();
  //     }
  //   });
  // }

  create() {
    this.items = Array(500);
  }

  remove() {
    this.items = Array(0);
  }
}

<!-- First render min options -->
<!-- <dx-button  *ngFor="let item of items"
  text="Click Me!"
>
</dx-button> -->

<!-- First render max options -->
<!-- <dx-button  *ngFor="let item of items"
  text="Click Me!"
  icon="download"
  accessKey="c"
  [activeStateEnabled]="true"
  [disabled]="false"
  hint="text hint"
  (click)="clickHandler()"
  [rtlEnabled]="true"
  [tabIndex]="1"
  [width]="100"
  height="40"
>
</dx-button> -->

<!-- First render template -->


<dx-button
  [template]="buttonTemplate"
  text="button-text"
>
</dx-button>
<ng-template #buttonTemplate let-text="text" let-icon="icon">
  <div>
    {{ text }}
  </div>
</ng-template>

<!-- Option change Icon -->
<!-- <button (click)="changeIcon()">
  change Icon
</button>
<dx-button  *ngFor="let item of items"
  text="button"
  [icon]="icon"
>
</dx-button> -->

<!-- Option change text -->
<!-- <button (click)="changeText()">
  change Text
</button>
<dx-button  *ngFor="let item of items"
  [text]="text"
>
</dx-button> -->

<!-- Option Change Max -->
<!-- <button (click)="changeOptions()">
  change options
</button>
<dx-button  *ngFor="let item of items"
  [text]="text"
  [icon]="icon"
  [accessKey]="accessKey"
  [disabled]="false"
  [hint]="hint"
  [rtlEnabled]="rtlEnabled"
  [tabIndex]="tabIndex"
  [width]="width"
  [height]="height"
>
</dx-button> -->

<!-- Method Focus -->
<!-- <button (click)="focus()">
  Call Focus
</button>
<dx-button  *ngFor="let item of items"
  [text]="text"
>
</dx-button> -->

<!-- Memory Leaks -->
<!-- <button (click)="create()">
  Create
</button>
<button (click)="remove()">
  Remove
</button>

<dx-button  *ngFor="let item of items"
  [text]="text"
>
</dx-button> -->
